# Define the system of units to use internally. 
InternalUnitSystem:
  UnitMass_in_cgs:     1.98848e43    # 10^10 M_sun
  UnitLength_in_cgs:   3.08567758e24 # 1 Mpc
  UnitVelocity_in_cgs: 1e5           # 1 km/s
  UnitCurrent_in_cgs:  1             # Amperes
  UnitTemp_in_cgs:     1             # Kelvin

# Planck-13 cosmology
Cosmology:
  h:              XXX
  a_begin:        XXX
  a_end:          XXX
  Omega_m:        XXX
  Omega_lambda:   XXX
  Omega_b:        XXX

# Parameters governing the time integration
TimeIntegration:
  dt_min:     1e-6 
  dt_max:     0.01

Scheduler:
  max_top_level_cells: 32
  cell_split_size:     200

# Parameters governing the snapshots
Snapshots:
  basename:            XXX
  delta_time:          1.02
  scale_factor_first:  0.02
  output_list_on:      1
  output_list:         ./snap_redshifts.txt
  invoke_stf:          0
  compression:         9
  subdir:              snapshots 

# Parameters governing the conserved quantities statistics
Statistics:
  delta_time:          1.02
  scale_factor_first:  0.02
 
# Restart files.
Restarts:
  enable:             1
  save:               1          # Keep copies
  onexit:             1
  subdir:             restart    # Sub-directory of the directory where SWIFT is run
  basename:           swift
  delta_hours:        4.0
  stop_steps:         100
  max_run_time:       71.5       # In hours
  resubmit_on_exit:   1
  resubmit_command:   ./auto_resubmit

# Parameters for the self-gravity scheme
Gravity:
  eta:                              0.025         
  comoving_DM_softening:            XXX
  comoving_baryon_softening:        XXX
  softening_ratio_background:       XXX
  max_physical_baryon_softening:    XXX
  max_physical_DM_softening:        XXX
  mesh_side_length:                 512
  MAC:                              adaptive
  theta_cr:                         0.7
  epsilon_fmm:                      0.001
  allow_truncation_in_MAC:          1
  use_tree_below_softening:         1

# Parameters related to the initial conditions
InitialConditions:
  file_name:                   XXX/XXX.hdf5
  periodic:                    1
  cleanup_h_factors:           1    
  cleanup_velocity_factors:    1  

StructureFinding:
  config_file_name:         none
  basename:                 stf
  output_list_on:           0
  output_list:              list.txt
  subdir_per_output:        stf
